### ISSUE TITLE
Issue connecting to company other than sandbox 

### ISSUE THREAD

**Issue by anitharoyappan** [IntuitDeveloper/QuickbooksV3API-DotNet-Mvc3-Sample#2]
When I connect to Quickbooks it lets me to connect only to sandbox company. How do I connect to the other company that I have access to? (https://qbo.intuit.com/app/homepage) ?

**Comment by nimisha84** [comment]
For sandbox testing, you need to use dev app keys and sandbox base url. 
For live/prod qbo company testing, use prod app keys and prod base url after doing a private publish as mentioned below. 
Go to your app->Prod tab-> enter all urls and save. Then get the prod keys from Keys tab under Prod tab of the app. 
Please refer- 
https://developer.intuit.com/v2/blog/2014/10/20/changes-to-ipp-app-tokens 
https://developer.intuit.com/blog/2014/10/24/intuit-developer-now-offers-quickbooks-sandboxes
